# Generated by Django 4.2.6 on 2024-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('last_status_date', models.DateField()),
                ('property_type', models.CharField(max_length=50)),
                ('sq_ft_total', models.IntegerField()),
                ('rooms_total', models.IntegerField()),
                ('beds_total', models.IntegerField()),
                ('baths_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('garage_parking_info', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nearby_amenities', models.TextField()),
                ('hoa_yn', models.BooleanField(default=False)),
                ('dom', models.IntegerField()),
                ('acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sqft_est_heated_above_grade', models.IntegerField(blank=True, null=True)),
                ('association_amenities', models.TextField(blank=True, null=True)),
                ('driveway_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zoning', models.CharField(blank=True, max_length=50, null=True)),
                ('handicap_features', models.BooleanField(default=False)),
                ('energy_features', models.TextField(blank=True, null=True)),
                ('hoa_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hoa_fee_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_owned_property', models.BooleanField(default=False)),
                ('high_school', models.CharField(blank=True, max_length=50, null=True)),
                ('elementary_school', models.CharField(blank=True, max_length=50, null=True)),
                ('swimming_pool_yn', models.BooleanField(default=False)),
                ('direct_waterfront_yn', models.BooleanField(default=False)),
                ('waterfront_description', models.CharField(blank=True, max_length=100, null=True)),
                ('price_change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('cooling_system', models.CharField(blank=True, max_length=50, null=True)),
                ('heat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('heat_fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('intermediate_school', models.CharField(blank=True, max_length=50, null=True)),
                ('exterior_features', models.TextField(blank=True, null=True)),
                ('middle_jr_high_school', models.CharField(blank=True, max_length=50, null=True)),
                ('pool_description', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_annual_heat_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
