# Generated by Django 4.2.6 on 2024-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_alter_house_assessed_value_alter_house_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='baths_total',
            field=models.CharField(max_length=5),
        ),
    ]
