# Generated by Django 4.2.6 on 2024-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0005_alter_house_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dom',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
