# Generated by Django 4.2.6 on 2024-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0006_alter_house_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(),
        ),
    ]
