# Generated by Django 4.2.6 on 2024-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0007_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='dom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
