# Generated by Django 4.2.6 on 2024-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0009_house_town_alter_house_property_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='assessed_value',
            field=models.IntegerField(null=True),
        ),
    ]
