# Generated by Django 4.2.6 on 2024-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0010_alter_house_assessed_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
